added white list
iqiyi/dpvs pull request #691
Opened 2020-12-07 12:11 UTC by ytwang0320

2020-12-10 12:45 UTC, ywc689 requested changes

2020-12-10 12:45 UTC, ywc689 commented on tools/ipvsadm/ipvsadm.c
> +	"wlst",
What's the purpose of "wlst" option?

2020-12-10 14:06 UTC, haosdent commented
Cool!

2021-01-15 06:41 UTC, ywc689 approved these changes

2021-01-18 02:44 UTC, ywc689 requested changes
Please adjust logs.

2021-01-18 02:44 UTC, ywc689 commented on src/ipvs/ip_vs_whtlst.c
> +    }
Don't log for EDPVS_NOTEXIST.

```
if (err && EDPVS_NOTEXIST) {
    RTE_LOG(INFO, SERVICE, "[%s] fail to del whtlst ip: %s\n", __func__, dpvs_strerror(err));
    return err;
}
```

2021-01-18 02:44 UTC, ywc689 commented on src/ipvs/ip_vs_whtlst.c
> +    }
Don't log for EDPVS_EXIST.

```
if (err && err != EDPVS_EXIST) {
    RTE_LOG(INFO, SERVICE, "[%s] fail to set whtlst ip: %s\n", __func__, dpvs_strerror(err));
    return err;
}
```

2021-01-19 01:44 UTC, ywc689 approved these changes

2021-01-20 07:05 UTC, merged